# Generated by Django 4.2.7 on 2026-02-13 16:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.TextField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('background_color', models.CharField(default='#FF6B6B', max_length=20)),
                ('text_color', models.CharField(default='#ffffff', max_length=20)),
                ('nav_color', models.CharField(default='#FF6B6B', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ads',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
