# Generated by Django 4.2.7 on 2026-02-13 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('shop_name', models.CharField(max_length=255)),
                ('seller_name', models.CharField(max_length=255)),
                ('main_category', models.CharField(max_length=100)),
                ('product_category', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('specifications', models.TextField(blank=True, null=True)),
                ('product_images', models.JSONField(default=list)),
                ('shop_image', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('currency', models.CharField(default='TZS', max_length=10)),
                ('price_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Negotiable', 'Negotiable')], default='Fixed', max_length=20)),
                ('stock_status', models.CharField(choices=[('Available', 'Available'), ('Limited', 'Limited'), ('Out of Stock', 'Out of Stock')], default='Available', max_length=20)),
                ('quantity_available', models.IntegerField(default=0)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used - Like New', 'Used - Like New'), ('Used - Good', 'Used - Good'), ('Used - Fair', 'Used - Fair'), ('Refurbished', 'Refurbished')], default='New', max_length=50)),
                ('warranty', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('warranty_period', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='Tanzania', max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('map_location', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-registration_date'],
            },
        ),
    ]
