# Generated by Django 4.2.7 on 2026-02-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_area_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, default='New', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_type',
            field=models.CharField(blank=True, default='Fixed', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(blank=True, default='Available', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, default='No', max_length=10, null=True),
        ),
    ]
