# Generated by Django 4.2.7 on 2026-02-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_condition_alter_product_price_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Used - Like New', 'Used - Like New'), ('Used - Good', 'Used - Good'), ('Used - Fair', 'Used - Fair'), ('Refurbished', 'Refurbished')], default='New', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_type',
            field=models.CharField(blank=True, choices=[('Fixed', 'Fixed'), ('Negotiable', 'Negotiable')], default='Fixed', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Limited', 'Limited'), ('Out of Stock', 'Out of Stock')], default='Available', max_length=20, null=True),
        ),
    ]
