# Generated by Django 4.2.7 on 2026-02-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_condition_alter_product_price_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-registration_date'], name='products_registr_b18239_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['main_category'], name='products_main_ca_ed3ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['email'], name='products_email_f42d8f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_is_acti_cb485f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-registration_date'], name='products_is_acti_cd6d23_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['main_category', 'is_active'], name='products_main_ca_9d1e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['email', 'is_active'], name='products_email_3a54dc_idx'),
        ),
    ]
