# Generated by Django 4.2.7 on 2026-02-27 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_products_registr_b18239_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_registr_b18239_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_main_ca_ed3ed9_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_email_f42d8f_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_is_acti_cb485f_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_is_acti_cd6d23_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_main_ca_9d1e7b_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_email_3a54dc_idx',
        ),
    ]
