# Generated by Django 4.2.7 on 2026-02-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_products_registr_b18239_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-registration_date'], name='idx_reg_date_desc'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['email'], name='idx_email'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='idx_is_active'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['main_category'], name='idx_main_category'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_category'], name='idx_product_category'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='idx_brand'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='idx_price'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['region'], name='idx_region'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['district'], name='idx_district'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-registration_date'], name='idx_active_date'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['main_category', 'is_active'], name='idx_category_active'),
        ),
    ]
